[package]
name = "chip8uwu"
version = "0.1.0"
authors = ["Seth"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = { git = "https://github.com/parasyte/pixels.git" }
winit = "0.24"
winit_input_helper = "0.9"
egui = "0.11"
egui_wgpu_backend = "0.6.0"
egui_winit_platform = "0.6"
log = "0.4"