[package]
name = "chip8uwu"
version = "0.1.0"
authors = ["Seth"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.13"
winit = "0.28"
winit_input_helper = "0.14"
egui = "0.22"
egui-wgpu = "0.22"
egui-winit = { version = "0.22", default-features = false, features = ["links"] }
native-dialog = "0.7"
log = "0.4"